@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Oct 18 14:32:58 +0800 2023
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim div2_tb_behav -key {Behavioral:sim_1:Functional:div2_tb} -tclbatch div2_tb.tcl -view C:/Users/Student/Desktop/ceng2010/ceng2010_lab5_q2/ceng2010_lab5_q2/div2_tb_behav.wcfg -log simulate.log"
call xsim  div2_tb_behav -key {Behavioral:sim_1:Functional:div2_tb} -tclbatch div2_tb.tcl -view C:/Users/Student/Desktop/ceng2010/ceng2010_lab5_q2/ceng2010_lab5_q2/div2_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
